'use client';

/**
 * FormField — the kit's form-row wrapper, consolidating the Chakra v3 `Field.*` idiom used across the
 * app (Field.Root → Label → control → HelperText / ErrorText; see CreatePayLinkForm.tsx) into one
 * component (frontendfeature.md §2.5). The control is passed as `children`, so callers keep full
 * control of the <Input> / <Textarea> / <NativeSelect> (value, type, fontFamily, …).
 *
 * a11y (F.6): Chakra associates the label with the control and sets `aria-invalid` / `aria-required` +
 * `aria-describedby` for the helper/error. Errors are conveyed as text with an icon (a non-color cue),
 * never by color alone — satisfying the error-state contract (F.5).
 */

import type { ReactNode } from 'react';
import { Box, Field } from '@chakra-ui/react';
import { AlertCircle } from 'react-feather';

export interface FormFieldProps {
  label: ReactNode;
  /** The form control (an <Input/>, <Textarea/>, <NativeSelect/>, …). */
  children: ReactNode;
  /** Persistent helper text, hidden while an error shows. */
  helperText?: ReactNode;
  /** Field error. When set, the field renders invalid and shows this in place of the helper text. */
  error?: string;
  required?: boolean;
  disabled?: boolean;
  /** Explicit id wired to label + control; auto-generated by Chakra when omitted. */
  id?: string;
  /** Optional trailing-of-label content (e.g. a Tooltip "?"). */
  labelAddon?: ReactNode;
}

export function FormField({
  label,
  children,
  helperText,
  error,
  required = false,
  disabled = false,
  id,
  labelAddon,
}: FormFieldProps) {
  return (
    <Field.Root invalid={Boolean(error)} required={required} disabled={disabled} id={id}>
      <Field.Label>
        {label}
        <Field.RequiredIndicator />
        {labelAddon ? (
          <Box as="span" ms="auto">
            {labelAddon}
          </Box>
        ) : null}
      </Field.Label>

      {children}

      {error ? (
        <Field.ErrorText color="status.danger" gap={1.5}>
          <AlertCircle size={14} aria-hidden />
          {error}
        </Field.ErrorText>
      ) : helperText ? (
        <Field.HelperText color="fg.muted">{helperText}</Field.HelperText>
      ) : null}
    </Field.Root>
  );
}
